# Generated by Django 3.2.18 on 2023-03-17 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20230317_1431'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField()),
                ('price', models.PositiveIntegerField()),
            ],
        ),
    ]
