# Generated by Django 3.2.18 on 2023-07-20 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20230720_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscription',
            name='sub_id',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
