# Generated by Django 3.2.18 on 2023-03-14 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0003_deck_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='flashcards',
            field=models.TextField(),
        ),
    ]
