# Generated by Django 3.2.18 on 2023-03-17 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0004_alter_deck_flashcards'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='anki',
            field=models.FileField(blank=True, null=True, upload_to='anki_files/'),
        ),
        migrations.AddField(
            model_name='deck',
            name='csv',
            field=models.FileField(blank=True, default='file.csv', null=True, upload_to='csv_files/'),
        ),
        migrations.AddField(
            model_name='deck',
            name='excl',
            field=models.FileField(blank=True, null=True, upload_to='excl_files/'),
        ),
    ]
