# Generated by Django 3.2.18 on 2023-03-18 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0005_auto_20230317_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='excl',
            field=models.FileField(blank=True, null=True, upload_to='xlsx_files/'),
        ),
    ]
