# Generated by Django 3.2.18 on 2023-03-18 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0006_alter_deck_excl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='anki',
            field=models.FileField(blank=True, null=True, upload_to='apkg_files/'),
        ),
    ]
