# Generated by Django 3.2.18 on 2023-03-20 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0008_auto_20230320_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='deck',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='flashcards.deck'),
            preserve_default=False,
        ),
    ]
